# Generated by Django 4.2.15 on 2024-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
