# Generated by Django 4.2.15 on 2024-08-27 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(default="Unknown", max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "Locations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Lockers",
            fields=[
                ("locker_id", models.AutoField(primary_key=True, serialize=False)),
                ("locker_number", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=9, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "Lockers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "reservation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "end_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reservations_end_location_set",
                        to="common.locations",
                    ),
                ),
                (
                    "end_locker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reservations_end_locker_set",
                        to="common.lockers",
                    ),
                ),
                (
                    "start_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.locations",
                    ),
                ),
                (
                    "start_locker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.lockers",
                    ),
                ),
            ],
            options={
                "db_table": "Reservations",
                "managed": True,
            },
        ),
    ]
