# Generated by Django 4.2.15 on 2024-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservations",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
